# -*- coding:utf-8 -*-

GROUP_USER_STATUS_FOLLOW = 0
GROUP_USER_STATUS_UNFOLLOW = 1
GROUP_USER_STATUS_BAN = 2

NOTICE_STATUS_UNREAD = 0
NOTICE_STATUS_READED = 1

SECRET_STATUS_NORMAL = 0
SECRET_STATUS_FORBIDDEN = 1

COMMENT_STATUS_NORMAL = 0
COMMENT_STATUS_FORBIDDEN = 1

USER_STATUS_NORMAL = 0
USER_STATUS_BAN = 1
USER_STATUS_FORBIDDEN = 2

GROUP_CATEGORY_SCHOOL = 1
GROUP_CATEGORY_TOPIC = 2
